services:
  libreoffice:
    image: linuxserver/libreoffice
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./storage/app/tmp:/data
    command: >
      bash -c "
      libreoffice
      --headless
      --nologo
      --nofirststartwizard
      --convert-to pdf
      --outdir /data
      "
    restart: unless-stopped
